# Generated by Django 3.1.7 on 2021-03-26 18:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('county', models.CharField(blank=True, max_length=30)),
                ('district', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basic.person')),
                ('position', models.CharField(max_length=30)),
            ],
            bases=('basic.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basic.person')),
                ('phonenum', models.IntegerField()),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dob', models.DateTimeField()),
                ('schoolyear', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('schoolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.school')),
            ],
            bases=('basic.person',),
        ),
    ]
