# Generated by Django 3.1.7 on 2021-04-12 22:13

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='School Name')),
                ('county', models.CharField(blank=True, max_length=30, verbose_name='County')),
                ('district', models.CharField(blank=True, max_length=30, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30, verbose_name='First Name')),
                ('lname', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('phonenum', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gradyear', models.IntegerField(blank=True, verbose_name='Graduation Year')),
                ('gender', models.CharField(max_length=30, verbose_name='Gender')),
                ('image', models.ImageField(blank=True, upload_to='profile_image', verbose_name='Profile')),
                ('race', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Caucasian'), (2, 'Hispanic'), (3, 'African American'), (4, 'Asian'), (5, 'American Indian'), (6, 'Pacific Islander')], max_length=11, verbose_name='Race')),
                ('shirt', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, verbose_name='Shirt size')),
                ('short', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, verbose_name='Short size')),
                ('student_ig', models.CharField(blank=True, max_length=30, verbose_name='Instagram Username')),
                ('favcandy', models.CharField(blank=True, max_length=30, verbose_name='Favorite Candy')),
                ('guard1fname', models.CharField(max_length=30, verbose_name='Guardian 1 First Name')),
                ('guard1sname', models.CharField(max_length=30, verbose_name='Guardian 1 Second Name')),
                ('guard1phonenum', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Guardian 1 Phone Number')),
                ('guard1email', models.EmailField(max_length=40, verbose_name='Guardian 1 Email')),
                ('gaurd1occ', models.CharField(blank=True, max_length=40, verbose_name='Guardian 1 Occupation')),
                ('guard1shirt', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, verbose_name='Guardian 1 Shirt size')),
                ('guard2fname', models.CharField(blank=True, max_length=30, verbose_name='Guardian 2 First Name')),
                ('guard2sname', models.CharField(blank=True, max_length=30, verbose_name='Guardian 2 Second Name')),
                ('guard2phonenum', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Guardian 2 Phone Number')),
                ('guard2email', models.EmailField(blank=True, max_length=40, verbose_name='Guardian 2 Email')),
                ('gaurd2occ', models.CharField(blank=True, max_length=40, verbose_name='Guardian 2 Occupation')),
                ('guard2shirt', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, verbose_name='Guardian 2 Shirt size')),
                ('emergcontact', models.CharField(choices=[('Guardian 1', 'Guardian 1'), ('Guardian 2', 'Guardian 2')], max_length=20, verbose_name='Emergency Contact')),
                ('comments', models.TextField(blank=True, verbose_name='Additional Comments')),
                ('schoolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.school', verbose_name='School')),
            ],
        ),
    ]
