# Generated by Django 3.1.7 on 2021-03-28 19:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20210328_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=30, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fname',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lname',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='county',
            field=models.CharField(blank=True, max_length=30, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.CharField(blank=True, max_length=30, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=50, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='student',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Additional Comments'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateTimeField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=30, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phonenum',
            field=models.IntegerField(blank=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='schoolid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.school', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='student',
            name='schoolyear',
            field=models.IntegerField(verbose_name='Year in School'),
        ),
    ]
