# Generated by Django 3.2 on 2021-05-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20210428_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='emergcontact',
            field=models.CharField(max_length=60, null=True, verbose_name='Emergency Contact'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guard1email',
            field=models.EmailField(max_length=50, null=True, verbose_name='Guardian 1 Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guard1occ',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Guardian 1 Occupation'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guard2email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Guardian 2 Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guard2occ',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Guardian 2 Occupation'),
        ),
        migrations.AlterField(
            model_name='student',
            name='race',
            field=models.CharField(max_length=40, null=True, verbose_name='Race'),
        ),
    ]
