# Generated by Django 3.1.7 on 2021-03-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20210328_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='schoolyear',
        ),
        migrations.AddField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2, verbose_name='Year in school'),
        ),
    ]
