# Generated by Django 3.2 on 2021-05-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20210504_1523'),
        ('basic', '0004_auto_20210504_1923'),
    ]

    operations = [
    ]
