# Generated by Django 3.2 on 2021-05-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_merge_0002_auto_20210504_1523_0004_auto_20210504_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=70, null=True, verbose_name='Gender'),
        ),
    ]
